// File generated by FlutterFire CLI.
//
// Run `flutterfire configure --project=<firebase-project-id>` to regenerate.
// Do NOT hand-edit; the CLI also drops google-services.json into android/app
// and GoogleService-Info.plist into ios/Runner.
//
// This stub keeps the codebase analyzeable before Firebase is configured.
// `Firebase.initializeApp()` will throw if the platform options are still
// the placeholder values below — startup catches that and continues without
// Firebase (the app still works, just no FCM / Analytics / Crashlytics).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Firebase configured only for iOS + Android.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'com.americantv.userapp',
  );

  static bool get isConfigured =>
      android.apiKey != 'REPLACE_ME' && ios.apiKey != 'REPLACE_ME';
}
